# Generated by Django 5.2.11 on 2026-05-02 01:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(help_text='Quién generó este token', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token Admin',
                'verbose_name_plural': 'Tokens Admin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del diseño, ej: Día de las Madres', max_length=120)),
                ('image', models.ImageField(help_text='Imagen de fondo de la tarjeta', upload_to='card_templates/')),
                ('is_active', models.BooleanField(default=False, help_text='Solo un template puede estar activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de Tarjeta',
                'verbose_name_plural': 'Templates de Tarjeta',
                'ordering': ['-created_at'],
            },
        ),
    ]
