# Generated by Django 5.2.11 on 2026-05-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtemplate',
            name='html_code',
            field=models.TextField(blank=True, default='', help_text='Código HTML/CSS del diseño generado por IA'),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen de fondo de la tarjeta', null=True, upload_to='card_templates/'),
        ),
    ]
