# Generated by Django 5.2.17 on 2026-10-01 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0002_cardtemplate_html_code_alter_cardtemplate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la empresa compradora', max_length=120)),
                ('logo', models.ImageField(help_text='Logo de la empresa', upload_to='company_logos/')),
                ('pos_x', models.FloatField(default=50, help_text='Centro del logo en el eje X (% del ancho de la tarjeta)')),
                ('pos_y', models.FloatField(default=50, help_text='Centro del logo en el eje Y (% del alto de la tarjeta)')),
                ('width', models.FloatField(default=25, help_text='Ancho del logo (% del ancho de la tarjeta)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Logo de Empresa',
                'verbose_name_plural': 'Logos de Empresa',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(help_text='Código del lote en SAP (U_Lote)', max_length=100, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='giftcards.companylogo')),
            ],
            options={
                'verbose_name': 'Lote de Empresa',
                'verbose_name_plural': 'Lotes de Empresa',
                'ordering': ['lote'],
            },
        ),
    ]
