# Generated by Django 5.2.17 on 2026-10-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0003_company_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylogo',
            name='rif',
            field=models.CharField(blank=True, default='', help_text='RIF con el que la empresa entra al portal; con él ve todas las tarjetas de sus lotes', max_length=30),
        ),
    ]
